# Generated by Django 3.1.4 on 2020-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('reviewScore', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='produtos',
            field=models.ManyToManyField(to='clientes.Produto'),
        ),
    ]
